### ISSUE TITLE
Where can we find the prohibited choices (禁忌肢)?

### ISSUE THREAD

**Issue by Coldog2333** [jungokasai/IgakuQA#1]
Hello, thank you for your contribution to this task.
I am interested in this topic and I am going to do some testing on it.

However, I cannot find the prohibited choices (禁忌肢) in your paper and this repository.

Could you tell me how to obtain this information?

**Comment by yumemio** [comment]
Disclaimer: I'm not a member of this repo, nor am I a medical professional, so take my words with a grain of salt. Clarification from the repo authors is welcome!

---

It would be impossible to tell which option is marked as prohibited, aside from people in MHLW (the government body responsible for conducting the exam), since information about these options is not disclosed to the public.

From [Kaneda et al. (2023)](https://www.preprints.org/manuscript/202303.0191/v1):

> Forbiddance options are choices that lead to the death of a patient or irreversible organ dysfunction or violate the laws that physicians should comply with. [...] However, it is not disclosed whether the Ministry of Health, Labor, and Welfare (MHLW), which is in charge of the national medical examination, has set it as a forbiddance option, [...]

...and from [a report from MHLW](https://www.mhlw.go.jp/content/10803000/000693879.pdf) on improving the national medical exam:

> 禁忌肢の公開についても、[...]問題の非公開化の議論の進捗とあわせ、教育的な効果等も考慮した上で、引き続き検討を行うことが望ましい
>
> Regarding the publication of the forbidden choices, it is desirable to continue deliberations, taking into account the educational effects and other factors, [...], and in conjunction with the progress of discussions on the non-disclosure of questions.

So, theoretically, we can't tell for sure which option is prohibited.

Regardless, [the paper](https://ar5iv.labs.arxiv.org/html/2303.18027)'s example of euthanasia is definitely one of them (it's so obvious even to the eyes of a layperson like me), which is a remarkable example that highlights the dangers of adopting GenAI without careful considerations.

**Comment by yumemio** [comment]
Scratch that. Prohibited choices are available as part of metadata.

For instance, metadata of the euthanasia question (Figure 1 in the paper) is [here](https://github.com/jungokasai/IgakuQA/blob/2bc4c3d159cf5505f6253d24a909fbd53237e239/data/2022/116-E_metadata.jsonl#L31). Here's the excerpt, formatted for readability:

```json
{
  ...
  "kinki": ["b"],
  "reason": "日本で安楽死は認められない",
  ...
}
```

The `kinki` (transliteration of 禁忌, meaning "prohibited") attribute provides the prohibited choices as an array, along with the reason.

Reading the paper further I found the passage below, which suggests that information about prohibited choices was extracted from some workbooks:

> We also collect additional metadata, such as the percentage of test takers who selected each choice, as well as the average accuracy of the test takers, based on the exam preparation books 国試対策問題編集委員会.

**Comment by jungokasai** [comment]
This is from an author. Thanks for the detailed, comprehensive reply @yumemio! I'm closing this issue.
